services:
  wp:
    image: defai_test:${WORDPRESS_VERSION:-6.6}-${PHP_VERSION:-8.4-rc}
    build:
      context: .docker/wp
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4-rc}
        WORDPRESS_VERSION: ${WORDPRESS_VERSION:-6.6}
    volumes:
      - .:/var/www/html/wp-content/plugins/defai
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "wppasswd"
      WORDPRESS_DEBUG: 0
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  nginx:
    image: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/wp-content/plugins/defai
      - wordpress:/var/www/html
    ports:
      - 80:80
    links:
      - wp:wp
    depends_on:
      - wp

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - 3306:3306 # change ip if required
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "wppasswd"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s
      retries: 10
      interval: 2s

volumes:
  db_data:
  wordpress:
