name: Behat Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT_LDAP: 3389
      PORT_LDAPS: 6363
      LDAP_ADMIN_PASSWORD: ${{ secrets.LDAP_ADMIN_PASSWORD }}
      LDAP_LOG_LEVEL: 0
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3']
        wordpress-version: ['6.4', '6.5', '6.6']

    name: Test on PHP ${{ matrix.php-version }}/WordPress ${{ matrix.wordpress-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Docker Compose Pull
        run: docker compose pull
      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true
      - name: Build the docker-compose stack
        run: docker compose build --build-arg PHP_VERSION=${{ matrix.php-version }} --build-arg WORDPRESS_VERSION=${{ matrix.wordpress-version }} wp
      - name: run the stack
        run: docker compose -f docker-compose.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker compose logs openldap
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phive
      - name: install dependencies
        run: composer install
      - name: install tools
        run: |
          mkdir -p tools
          curl -Lo tools/behat https://github.com/Behat/Behat/releases/download/v3.13.0/behat.phar
          chmod 755 tools/behat
      - name: run behat
        run: docker compose exec wp bash -c "cd wp-content/plugins/authldap && ./tools/behat"
      - name: Check logs
        if: ${{ failure() }}
        run: docker compose logs
