name: Build
on:
  push:
    tags:
      - '**'
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: write
    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: phive
      - name: Install dependencies
        run: composer install --prefer-dist --no-dev -a
      - name: Create archive
        run: |
          rm -rf defai
          mkdir defai
          git archive --prefix="./" --format=tar ${{ github.ref }} . | tar xv -C defai/
          find defai -type f -exec sed -i 's/%tag%/${{ github.ref_name }}/' {} \;
          cat defai/readme.txt
          mv vendor defai/
          rm defai/composer.json defai/composer.lock
          zip -r defai.zip defai
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "defai.zip"
          generateReleaseNotes: true
          makeLatest: true
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: false
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          BUILD_DIR: defai
          SLUG: defai

