name: Build
on:
  push:
    tags:
      - '**'
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: write
    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: phive
      - name: Install dependencies
        run: composer install --prefer-dist --no-dev -a
      - name: Create archive
        run: |
          rm -rf defai
          mkdir defai
          git archive --prefix="./" --format=tar ${{ github.ref }} . | tar xv -C defai/
          find defai -type f -exec sed -i 's/\$Format:%(describe)\$/${{ github.ref }}/' {} \;
          mv vendor defai/
          zip -r defai.zip defai
          rm -rf defai
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "defai.zip"
          generateReleaseNotes: true
          makeLatest: true

